name: CI Pipeline

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      
      - name: Display Message
        run: echo "Hello, GitHub Actions!"

      - name: List Files
        run: ls -la
